env: 
  global: 
    secure: "A2yfij1/Xd6c1qPz+HNFKKLBSWFLNLSEF08P6kLiwt3geiMTTAWQ0EF+lhzR9Jc8nYzms7gmoB10mD5xNGVsfLc0MvcvoEEyMiHSeV+GkUXOrje+/+ZISJkxPbQnrU9y8VYDa25AEt3084bBz1R63RbkGoqQlWF6cqQFTUwUr/I="

addons: 
  coverity_scan: 
    project: 
      name: daniel-kun/omni
    build_command_prepend: mkdir cbuild && cd cbuild && CXX=clang++-3.5 cmake ..
    build_command: make -j4
    branch_pattern: coverity_scan
    notification_email: d.albuschat@gmail.com
after_script: mkdir ../tests && ./omni-tests
export COVERITY_SCAN_TOKEN=hB1FTnJx8XhjRffMZgIeVA: 
  secure: l9t1xEBIonK67fPZKUrI9n88L+yEmZWoSadCbKsG8csFBoivh53M8fazR5yt88z4CiASQsmhRXjRLsjUgVnN7Dc0YCnoyAZ6d5WTqwb9s4AAuf40Mv9eA6Thq67xiWzLzZq6qvs1lhVmlXQo9pUU0Dk/pNTTfSQgsdA0Gi52YQ4=
before_install: sudo sh -c 'cat build/ubuntu12/sources.list >> /etc/apt/sources.list' && sudo apt-get update
script: mkdir cbuild && cd cbuild && CXX=clang++-3.5 cmake .. && make
language: c++
install: sudo apt-get install --force-yes libncurses-dev libboost1.48-all-dev clang-3.5 libllvm3.5
