env: 
  global: 
    secure: "A2yfij1/Xd6c1qPz+HNFKKLBSWFLNLSEF08P6kLiwt3geiMTTAWQ0EF+lhzR9Jc8nYzms7gmoB10mD5xNGVsfLc0MvcvoEEyMiHSeV+GkUXOrje+/+ZISJkxPbQnrU9y8VYDa25AEt3084bBz1R63RbkGoqQlWF6cqQFTUwUr/I="

addons: 
  coverity_scan: 
    project: 
      name: daniel-kun/omni
    build_command_prepend: mkdir cbuild && cd cbuild && cmake ..
    build_command: make -j4
    branch_pattern: coverity_scan
    notification_email: d.albuschat@gmail.com

language: c++
before_install: sudo sh -c 'cat build/ubuntu12/sources.list >> /etc/apt/sources.list' && sudo apt-get install python-software-properties && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update
install: sudo apt-get install --force-yes qt5-default gcc-4.8 g++-4.8 libncurses-dev libboost1.48-all-dev clang-3.6 libllvm3.6 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then mkdir cbuild && cd cbuild && cmake -DCMAKE_CXX_COMPILER=clang-3.6 .. && make -j4 && mkdir ../tests && ./omni-tests; fi
