language: c++
before_install: sudo sh 'cat build/ubuntu12/sources.list > /etc/apt/sources.list'
install: sudo apt-get install libncurses-dev libboost-all-dev clang-3.5 libllvm3.5
script: CXX=clang++ mkdir cbuild && cd cbuild && cmake .. && make
after_script: mkdir ../tests && ./omni-tests


