env: 
  global: 
    secure: I/8p/+MUJVBLCmoyWhfonQCTRVaidkEJb8RRWSBA5IioW10Pf/oDtM1Bg4GGxN7ewEGQfEyPVMwVFGoU8+jrxsWsAyqe8HkzIA5Pe943HqdodO5ChnBPeDUock0Y8cFFdXt9WHvyiHfZHXxgYEDgMCghZiTUud7Hbv5tRZD9+so=

language: c++
before_install: sudo sh -c 'cat build/ubuntu12/sources.list >> /etc/apt/sources.list' && sudo apt-get update
install: sudo apt-get install --force-yes libncurses-dev libboost1.48-all-dev clang-3.5 libllvm3.5
script: mkdir cbuild && cd cbuild && CXX=clang++-3.5 cmake .. && make
after_script: mkdir ../tests && ./omni-tests

addons:
  coverity_scan:
    project:
      name: "daniel-kun/omni"
    notification_email: d.albuschat@gmail.com
    build_command_prepend: mkdir cbuild && cd cbuild && CXX=clang++-3.5 cmake ..
    build_command: make -j4
    branch_pattern: coverity_scan

