henv: 
  global: 
    secure: "A2yfij1/Xd6c1qPz+HNFKKLBSWFLNLSEF08P6kLiwt3geiMTTAWQ0EF+lhzR9Jc8nYzms7gmoB10mD5xNGVsfLc0MvcvoEEyMiHSeV+GkUXOrje+/+ZISJkxPbQnrU9y8VYDa25AEt3084bBz1R63RbkGoqQlWF6cqQFTUwUr/I="

addons: 
  coverity_scan: 
    project: 
      name: daniel-kun/omni
    build_command_prepend: mkdir build && cd build && cmake ..
    build_command: make -j4
    branch_pattern: coverity_scan
    notification_email: d.albuschat@gmail.com

language: c++
before_install: sudo sh -c 'cat platforms/ubuntu12/sources.list >> /etc/apt/sources.list' && sudo apt-get install python-software-properties && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa && sudo apt-add-repository -y ppa:kalakris/cmake && sudo apt-get update
install: sudo apt-get install --force-yes qt5-default 'cmake=2.8.11.2-1ubuntu2~precise1' gcc-4.8 g++-4.8 libncurses-dev libboost1.48-all-dev clang-3.6 libllvm3.6 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50 && sudo sh ./workarounds/llvm_ubuntu_12.04.cmake.fix
script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=g++-4.8 .. && make -j4 && mkdir ../tests && ./omni-tests; fi
