language: c++
before_install: sudo sh -c 'cat build/ubuntu12/sources.list >> /etc/apt/sources.list' && sudo apt-get update
install: sudo apt-get install --force-yes libncurses-dev libboost1.48-all-dev clang-3.5 libllvm3.5
script: CXX=clang++-3.5 mkdir cbuild && cd cbuild && cmake .. && make
after_script: mkdir ../tests && ./omni-tests


